name: CommitAction

on:
  commit:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Initialise environment
        run: cat ".github-env-$GITHUB_BASE_REF" >> $GITHUB_ENV

      - name: Fetch git repository
        uses: actions/checkout@v2

      - name: Restore build
        run: /srv/github-action-scripts/restore-site-build.sh

      - name: Build site
        run: /srv/github-action-scripts/build-jekyll-site.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Preserve build
        run: /srv/github-action-scripts/preserve-site-build.sh

  check-links:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Initialise environment
        run: cat ".github-env-$GITHUB_BASE_REF" >> $GITHUB_ENV

      - name: Check links
        run: /srv/github-action-scripts/check-links.sh

  test-routing-rules:
    needs: check-links
    runs-on: self-hosted
    steps:
      - name: Check routing rules
        run: /srv/github-action-scripts/test-routing-rules.sh
