name: BuildAndPublishSite

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Display workspace directory contents
        run: cd "$GITHUB_WORKSPACE" && ls

      - name: Display environment
        run: env

      - name: Output event payload
        run: cat "$GITHUB_EVENT_PATH"
