name: PushAction

on:
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Initialise environment
        run: cat ".github-env-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Fetch git repository
        uses: actions/checkout@v2

      - name: Directory push/pop
        uses: linaro-its/directory-push-and-pop@v1
        with:
          cacheDirectory: /srv/site-builds
          namedDirectory: $SITE_URL

      - name: Build site
        run: /srv/github-action-scripts/build-jekyll-site.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-links:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Initialise environment
        run: cat ".github-env-$GITHUB_BASE_REF" >> $GITHUB_ENV

      - name: Check links
        run: /srv/github-action-scripts/check-links.sh

  test-routing-rules:
    needs: check-links
    runs-on: self-hosted
    steps:
      - name: Check routing rules
        run: /srv/github-action-scripts/test-routing-rules.sh
