name: ScheduledBuild

# This workflow will run on the schedule defined below in order to trigger
# a rebuild of the website.
#
# To avoid problems, the cron schedule should be for a **SPECIFIC DATE AND TIME**
#
# The cron fields are:
# minute (0-59)
# hour (0-23)
# day of the month (1-31)
# month (1-12)
# day of the week (0-6)


on:
  schedule:
    - cron: '50 11 30 10 *'
  schedule:
    - cron: '55 11 30 10 *'

jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - name: Trigger site rebuild
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: PushAction
          token: ${{ secrets.SCHEDULE_TOKEN }}
